package com.lzh.gitstar;

import com.alibaba.fastjson.JSON;
import com.lzh.gitstar.domain.graphql.JsonRootBean;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@SpringBootTest
public class GitStarApplicationTests {


	@Test
	public void contextLoads() {
	}

	public static void main(String[] args) {
		String result = "{\n"
			+ "\t\"data\": {\n"
			+ "\t\t\"rateLimit\": {\n"
			+ "\t\t\t\"cost\": 1,\n"
			+ "\t\t\t\"nodeCount\": 211,\n"
			+ "\t\t\t\"remaining\": 4997,\n"
			+ "\t\t\t\"resetAt\": \"2019-10-31T07:56:59Z\"\n"
			+ "\t\t},\n"
			+ "\t\t\"user\": {\n"
			+ "\t\t\t\"avatarUrl\": \"https://avatars0.githubusercontent.com/u/45585937?v=4\",\n"
			+ "\t\t\t\"company\": \"@vlang\",\n"
			+ "\t\t\t\"createdAt\": \"2018-12-04T06:10:31Z\",\n"
			+ "\t\t\t\"followers\": {\n"
			+ "\t\t\t\t\"totalCount\": 11\n"
			+ "\t\t\t},\n"
			+ "\t\t\t\"contributionsCollection\": {\n"
			+ "\t\t\t\t\"totalCommitContributions\": 203,\n"
			+ "\t\t\t\t\"totalRepositoryContributions\": 29,\n"
			+ "\t\t\t\t\"totalPullRequestContributions\": 2,\n"
			+ "\t\t\t\t\"contributionYears\": [2019, 2018]\n"
			+ "\t\t\t},\n"
			+ "\t\t\t\"organizations\": {\n"
			+ "\t\t\t\t\"totalCount\": 7,\n"
			+ "\t\t\t\t\"nodes\": [{\n"
			+ "\t\t\t\t\t\"name\": \"B3log 开源社区\",\n"
			+ "\t\t\t\t\t\"avatarUrl\": \"https://avatars1.githubusercontent.com/u/1627618?v=4\"\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"name\": \"FUCK-THE-GIRL-FRIEND\",\n"
			+ "\t\t\t\t\t\"avatarUrl\": \"https://avatars2.githubusercontent.com/u/46474891?v=4\"\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"name\": \"Go Cloud\",\n"
			+ "\t\t\t\t\t\"avatarUrl\": \"https://avatars0.githubusercontent.com/u/47104367?v=4\"\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"name\": \"Python Cloud\",\n"
			+ "\t\t\t\t\t\"avatarUrl\": \"https://avatars0.githubusercontent.com/u/47135404?v=4\"\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"name\": \"TheGreatJavaScript\",\n"
			+ "\t\t\t\t\t\"avatarUrl\": \"https://avatars1.githubusercontent.com/u/47150361?v=4\"\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"name\": \"泸溪职中网页组\",\n"
			+ "\t\t\t\t\t\"avatarUrl\": \"https://avatars3.githubusercontent.com/u/48265348?v=4\"\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"name\": \"用爱发电\",\n"
			+ "\t\t\t\t\t\"avatarUrl\": \"https://avatars0.githubusercontent.com/u/56310988?v=4\"\n"
			+ "\t\t\t\t}]\n"
			+ "\t\t\t},\n"
			+ "\t\t\t\"repositories\": {\n"
			+ "\t\t\t\t\"totalCount\": 39,\n"
			+ "\t\t\t\t\"nodes\": [{\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"Programming-With-Love/dd1024\",\n"
			+ "\t\t\t\t\t\"forkCount\": 2,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"JavaScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 3\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 41\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/mm\",\n"
			+ "\t\t\t\t\t\"forkCount\": 2,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"CSS\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 6\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/lovepack\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"Python\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 1\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 2\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/huluxia\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"CSS\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 2\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/MoePiku\",\n"
			+ "\t\t\t\t\t\"forkCount\": 2,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"JavaScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 2\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/onion\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"HTML\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 1\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"luxizhizhong/upx\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"JavaScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"luxizhizhong/1024\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"Python\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/ssr-xo\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": null,\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 1\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"luxizhizhong/color-picker\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"JavaScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"luxizhizhong/querystring\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"JavaScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"luxizhizhong/CloudMusic\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"JavaScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"luxizhizhong/getPic\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"JavaScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/pure-bash-bible\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"Shell\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/flutter-todos\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"Dart\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/noting\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"Python\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 1\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/kwai-api\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"JavaScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 1\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/macbook-pro-setup\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": null,\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/bash-guide\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": null,\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/countdown\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"Go\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/Kugou-api\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": null,\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/linuv\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": null,\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 1\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/bug.n\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"AutoHotkey\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"luxizhizhong/API-next\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": null,\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"luxizhizhong/middle\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"JavaScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"luxizhizhong/jQuery-quick\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"JavaScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/random\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"Vue\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/theapi\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"JavaScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/bb\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"JavaScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/Mozx\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"PHP\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/deno\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"TypeScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/q.js\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"JavaScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/ws\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"JavaScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/eyes\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"HTML\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/prerender-loader\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"JavaScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/Anime-Girls-Holding-Programming-Books\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": null,\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/nsfw_data_scrapper\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"Shell\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/d1y.github.io\",\n"
			+ "\t\t\t\t\t\"forkCount\": 1,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"JavaScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"d1y/dotfiles\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"Shell\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}]\n"
			+ "\t\t\t},\n"
			+ "\t\t\t\"repositoriesContributedTo\": {\n"
			+ "\t\t\t\t\"totalCount\": 15,\n"
			+ "\t\t\t\t\"nodes\": [{\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"electron/apps\",\n"
			+ "\t\t\t\t\t\"forkCount\": 964,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"JavaScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 116\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 963\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"luxizhizhong/share\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": null,\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 2\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 1\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"luxizhizhong/huluxia\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"JavaScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 3\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"luxizhizhong/theapi\",\n"
			+ "\t\t\t\t\t\"forkCount\": 1,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"JavaScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"fuckGirlfriend/mm-cli\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"JavaScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"fuckGirlfriend/meizi\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"JavaScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"luxizhizhong/jQuery-quick\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"JavaScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"luxizhizhong/middle\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"JavaScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"luxizhizhong/API-next\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": null,\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"luxizhizhong/getPic\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"JavaScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"luxizhizhong/querystring\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"JavaScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"luxizhizhong/color-picker\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"JavaScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"luxizhizhong/1024\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"Python\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"Programming-With-Love/dd1024\",\n"
			+ "\t\t\t\t\t\"forkCount\": 2,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"JavaScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 3\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 41\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}, {\n"
			+ "\t\t\t\t\t\"nameWithOwner\": \"luxizhizhong/upx\",\n"
			+ "\t\t\t\t\t\"forkCount\": 0,\n"
			+ "\t\t\t\t\t\"primaryLanguage\": {\n"
			+ "\t\t\t\t\t\t\"name\": \"JavaScript\"\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"watchers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t},\n"
			+ "\t\t\t\t\t\"stargazers\": {\n"
			+ "\t\t\t\t\t\t\"totalCount\": 0\n"
			+ "\t\t\t\t\t}\n"
			+ "\t\t\t\t}]\n"
			+ "\t\t\t},\n"
			+ "\t\t\t\"topRepositories\": {\n"
			+ "\t\t\t\t\"totalCount\": 86,\n"
			+ "\t\t\t\t\"nodes\": [null]\n"
			+ "\t\t\t}\n"
			+ "\t\t}\n"
			+ "\t}\n"
			+ "}";
		JsonRootBean jsonRootBean = JSON.parseObject(result, JsonRootBean.class);
	}

}
